chore: update repository for new standardization
vuestorefront/ecommerce-integration-boilerplate pull request #13
Opened 2021-08-03 19:28 UTC by bloodf

With the PR, we will put the boilerplate into a new process of development

2021-08-17 13:21 UTC, andrzejewsky approved these changes

2021-08-17 13:26 UTC, filipsobol commented on packages/theme/nuxt.config.js
> -  // Global page headers: https://go.nuxtjs.dev/config-head
Please restore all these comments, as they might be useful for integrators or end developers

2021-08-17 16:12 UTC, bloodf commented on packages/theme/nuxt.config.js
> -  // Global page headers: https://go.nuxtjs.dev/config-head
Fixed

2021-08-17 22:17 UTC, bloodf commented
Can you recheck @filipsobol

2021-08-18 07:17 UTC, filipsobol requested changes
I tried running the command from the README file, but it doesn't work for me.

```
fsobol:~/Projects/Boilerplate_copy$ grep -rl '<% INTEGRATION %>' ./ | xargs sed -i '' 's/<% INTEGRATION %>/sloth/g'
sed: can't read s/<% INTEGRATION %>/sloth/g: No such file or directory
```

2021-08-18 07:17 UTC, filipsobol commented on .vuestorefrontcloud/docker/docs/Dockerfile
> +FROM node:12 AS build
If we require Node v14, then we should also use it for testing and deployment too

2021-08-19 16:15 UTC, filipsobol approved these changes

2021-08-19 17:06 UTC, merged